name: iOS Build Only

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest # iOS builds require a macOS environment

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS App Bundle (unsigned)
        run: flutter build ios --release --no-codesign

      - name: Create unsigned iOS IPA
        run: |
          mkdir Payload
          cp -R build/ios/iphoneos/Runner.app Payload/Runner.app
          zip -q -r app-release.ipa Payload

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: app-release.ipa